SCHEMES = [
    {
        "id": "nsp_sc_postmatric",
        "name": "Post-Matric Scholarship for SC Students",
        "category": "SC",
        "income_limit_lakh": 2.5,
        "purpose": "education",
        "state": "All India",
        "eligibility_text": "SC students in post-matriculation/post-secondary courses at recognized institutions with family income below ₹2.5 lakh/year are eligible.",
        "documents_required": [
            "Aadhaar card",
            "caste certificate",
            "income certificate",
            "bank passbook",
            "previous marksheet",
            "institution bonafide certificate",
        ],
        "how_to_apply": "Apply on National Scholarship Portal (scholarships.gov.in).",
    },
    {
        "id": "prematric_minority",
        "name": "Pre-Matric Scholarship for Minorities",
        "category": "Minority",
        "income_limit_lakh": 1.0,
        "purpose": "education",
        "state": "All India",
        "eligibility_text": "Students from notified minority communities (Muslim, Christian, Sikh, Buddhist, Parsi, Jain) in classes 1-10 with family income below ₹1 lakh/year are eligible.",
        "documents_required": [
            "Aadhaar card",
            "minority community certificate",
            "income certificate",
            "school bonafide certificate",
            "bank passbook",
        ],
        "how_to_apply": "Apply on National Scholarship Portal (scholarships.gov.in).",
    },
    {
        "id": "pm_yasasvi",
        "name": "PM YASASVI Scholarship",
        "category": "OBC/EBC/DNT",
        "income_limit_lakh": 2.5,
        "purpose": "education",
        "state": "All India",
        "eligibility_text": "Students from OBC, EBC, or Denotified Tribe communities in classes 9-12 with family income below ₹2.5 lakh/year are eligible.",
        "documents_required": [
            "Aadhaar card",
            "caste/community certificate",
            "income certificate",
            "previous year marksheet",
            "bank passbook",
        ],
        "how_to_apply": "Apply on National Scholarship Portal (scholarships.gov.in).",
    },
    {
        "id": "ayushman_bharat",
        "name": "Ayushman Bharat – PM-JAY",
        "category": "Any",
        "income_limit_lakh": None,
        "purpose": "health",
        "state": "All India",
        "eligibility_text": "Households identified as deprived/vulnerable under the SECC 2011 database are eligible for coverage up to ₹5 lakh/year for hospitalization.",
        "documents_required": [
            "Aadhaar card",
            "ration card",
            "SECC/PM-JAY eligibility verification",
        ],
        "how_to_apply": "Apply via pmjay.gov.in or nearest empanelled hospital.",
    },
    {
        "id": "pm_awas_yojana",
        "name": "Pradhan Mantri Awas Yojana",
        "category": "EWS/LIG",
        "income_limit_lakh": 3.0,
        "purpose": "housing",
        "state": "All India",
        "eligibility_text": "Households from Economically Weaker Section or Low Income Group that do not own a pucca house and are within the applicable income slab are eligible.",
        "documents_required": [
            "Aadhaar card",
            "income certificate",
            "bank passbook",
            "property/land documents if any",
            "photograph",
        ],
        "how_to_apply": "Apply at pmaymis.gov.in (urban) or pmayg.nic.in (rural).",
    },
    {
        "id": "nhfdc_disability_loan",
        "name": "NHFDC Loan Scheme for Persons with Disabilities",
        "category": "Any",
        "income_limit_lakh": None,
        "purpose": "disability",
        "state": "All India",
        "eligibility_text": "Persons with 40%+ disability certificate seeking self-employment or business loans are eligible.",
        "documents_required": [
            "Aadhaar card",
            "disability certificate",
            "project/business plan",
            "bank details",
        ],
        "how_to_apply": "Apply through nhfdc.nic.in via State Channelising Agency.",
    },
    {
        "id": "sukanya_samriddhi",
        "name": "Sukanya Samriddhi Yojana",
        "category": "Any",
        "income_limit_lakh": None,
        "purpose": "women",
        "state": "All India",
        "eligibility_text": "Parents or guardians of a girl child under 10 years can open a high-interest savings account with tax benefits.",
        "documents_required": [
            "girl child's birth certificate",
            "parent/guardian Aadhaar card",
            "address proof",
        ],
        "how_to_apply": "Apply at any post office or authorized bank branch.",
    },
    {
        "id": "nmms",
        "name": "National Means-cum-Merit Scholarship",
        "category": "General",
        "income_limit_lakh": 1.5,
        "purpose": "education",
        "state": "All India",
        "eligibility_text": "Class 9 students (continuing through class 12) in government or government-aided schools with family income below ₹1.5 lakh/year who clear the NMMS exam are eligible.",
        "documents_required": [
            "Aadhaar card",
            "income certificate",
            "school bonafide certificate",
            "exam scorecard",
        ],
        "how_to_apply": "Apply through state education department or NSP portal.",
    },
    {
        "id": "kanyashree",
        "name": "West Bengal Kanyashree Prakalpa",
        "category": "Any",
        "income_limit_lakh": 1.2,
        "purpose": "women",
        "state": "West Bengal",
        "eligibility_text": "Unmarried girls aged 13-18 enrolled in school or college in West Bengal with family income below ₹1.2 lakh/year are eligible for annual scholarship (K1) and one-time grant at 18 (K2) if unmarried and still studying.",
        "documents_required": [
            "Aadhaar card",
            "birth certificate",
            "income certificate",
            "bank passbook",
            "school/college bonafide certificate",
        ],
        "how_to_apply": "Apply at wbkanyashree.gov.in.",
    },
    {
        "id": "swasthya_sathi",
        "name": "West Bengal Swasthya Sathi",
        "category": "Any",
        "income_limit_lakh": None,
        "purpose": "health",
        "state": "West Bengal",
        "eligibility_text": "West Bengal resident families are eligible for universal health coverage up to ₹5 lakh/year hospitalization with women as primary cardholders.",
        "documents_required": [
            "Aadhaar card",
            "WB residence proof",
            "family enrollment details",
        ],
        "how_to_apply": "Apply at swasthyasathi.gov.in or nearest BDO office/enrollment camp.",
    },
]